### ISSUE TITLE
Does the offerer need to be prepared to receive media on multiple potential ports?

### ISSUE THREAD

**Issue by taylor-b** [cdh4u/draft-sdp-bundle#20]
If an "m=" section offers fallback to being non-bundled, should the offerer be prepared to receive media for that "m=" section on both the BUNDLE address and the fallback address? This isn't explicitly stated anywhere, but may have been assumed.

One difficulty in fulfilling that requirement is that the answerer is able to select the answerer BUNDLE-section and thus the BUNDLE address. So if offering three "m=" sections, the media for the third "m=" section might be received on any of the three offered addresses.

**Comment by cdh4u** [comment]
The offerer needs to be prepared to receive media on the fallback addresses. Of course, if ICE is used, and the answerer indicates support of BUNDLE, the offerer won't initiate any ICE procedures on the fallback addresses.

Without ICE, one option would be to mandate the answerer to select the port:address that is preferred by the offerer (first tag in the a=group:BUNDLE attribute), unless the answerer rejects the tag (m- line) associated with that port:address. 

Another option is to indicate all-but-one m- line as bundle-only (port zero). Then, if the answerer does not support/accept BUNDLE, you send a new (non-bundled) offer. Obviously that requires 2 O/A transactions, but you don't have to reserve ports "just in case".

**Comment by taylor-b** [comment]
Ok; I think this should be documented somewhere in the "Generating an Offer" section, then. It's not a conclusion you intuitively come to, until you realize there are conditions where an answerer will select a different offerer BUNDLE-tag.

Also: the solution to just use "bundle-only" doesn't work, due to this issue: https://github.com/cdh4u/draft-sdp-bundle/issues/22

**Comment by cdh4u** [comment]
Just to clarify, you want to document the fact that the offerer needs to be able to receive media on all addresses, before the BUNDLE group has been accepted by the answerer?

**Comment by taylor-b** [comment]
Yes. Though, technically, since the answerer is required to select the first BUNDLE-tag that remains in the BUNDLE group, it's a little more complex. If you have an offer like:

```
a=group:BUNDLE A B C
m=audio 2000
a=mid:A
...
m=audio 3000
a=mid:B
...
m=audio 4000
a=mid:C
```

Then the media for A can arrive only on port 2000, media for B can arrive on port 2000 or 3000, and media for C can arrive on any of the three ports.

**Comment by cdh4u** [comment]
Version -44 will clarify this.
