### ISSUE TITLE
When is "a=bundle-only" invalid?

### ISSUE THREAD

**Issue by taylor-b** [cdh4u/draft-sdp-bundle#23]
These two statements seem contradictory to me:

>   The usage of the 'bundle-only' attribute is only defined for a
>   bundled "m=" line with a zero port value, within an offer.  Other
>   usage is unspecified.

>   The answerer MUST NOT associate an SDP 'bundle-only' attribute with
>   any "m=" line in an answer.

May want to clarify that although implementations of this specification will not generate 'bundle-only' in an answer, they should be prepared to receive it and not treat it as an error.

**Comment by cdh4u** [comment]
I think Adam raised a similar issue on the list.

https://www.ietf.org/mail-archive/web/mmusic/current/msg17252.html

**Comment by cdh4u** [comment]
bundle-only can now be used in both offers and answers.
