### ISSUE TITLE
Restrictions for offering unique addresses in a subsequent offer seem unnecessary.

### ISSUE THREAD

**Issue by taylor-b** [cdh4u/draft-sdp-bundle#25]
I'm referring to this list of conditions:

>   When an offerer generates a subsequent offer, it MUST associate the
>   previously selected offerer BUNDLE address [Section 8.3.1] with each
>   bundled "m=" line (including any bundle-only "m=" line), except if:
>
>   o  The offerer suggests a new offerer BUNDLE address [Section 8.5.1];
>      or
>
>   o  The offerer wants to add a bundled "m=" line to the BUNDLE group
>      [Section 8.5.2]; or
>
>   o  The offerer wants to move a bundled "m=" line out of the BUNDLE
>      group [Section 8.5.3]; or
>
>   o  The offerer wants to disable the bundled "m=" line
>      [Section 8.5.4].

My interpretation is: If A, B and C are already bundled, then a subsequent offer MUST use a shared address for them. But if D is added, then A, B, C, and D can use unique addresses.

I don't see what value this restriction provides. Also, an endpoint could just add a dummy "m=" section to get around this restriction. So I'd recommend removing it.

**Comment by cdh4u** [comment]
Some clarification might be needed, but the bullets apply to individual m- lines. 

So, it is perfectly ok to add D, and use A,B and C with a unique address.

(Of course, this issue is dependent on your other issue, whether unique addresses should be dropped completely.)

**Comment by cdh4u** [comment]
Now, in a subsequent offer, the BUNDLE address is only assigned to the m= section represented by the BUNDLE-tag.
