### ISSUE TITLE
Explicitly allow RTP-relevant parameters in data channel m= sections

### ISSUE THREAD

**Issue by ekr** [cdh4u/draft-sdp-bundle#27]
This can happen if (for instance) you have a data channel and then renegotiate to add media.

**Comment by cdh4u** [comment]
This was discussed at some point, and the outcome was that we should not allow it, because we would have to update RTP-specific parameter (rtcp attribute, rtcp-mux attribute etc) specifications in order to allow them in non-RTP m- sections.

Why can't you later add the RTP-specific parameters together with the RTP m- sections?

**Comment by ekr** [comment]
The On Wed, Feb 15, 2017 at 1:39 PM, cdh4u <notifications@github.com> wrote:

> This was discussed at some point, and the outcome was that we should not
> allow it, because we would have to update RTP-specific parameter (rtcp
> attribute, rtcp-mux attribute etc) specifications in order to allow them in
> non-RTP m- sections.
>

Yeah, the JSEP editor team thinks it needs reconsideration.

Why can't you later add the RTP-specific parameters together with the RTP
> m- sections?
>

As far as we can tell, BUNDLE forbids it, because they are of type
IDENTICAL or TRANSPORT, so they can only appear in the m= section with the
bundle tag.

-Ekr

**Comment by cdh4u** [comment]
>> Why can't you later add the RTP-specific parameters together with the RTP m- sections?

> As far as we can tell, BUNDLE forbids it, because they are of type IDENTICAL or TRANSPORT, so they 
> can only appear in the m= section with the bundle tag.

Well, you can change the bundle tag when adding the RTP media.

...OR, we need to change the mux category, and either:

1) Clarify that the mux category rules only apply to RTP streams; or
2) Change the category to SPECIAL, and then describe that it only applies to RTP streams.

In any case, I think this issue should be brought to the list.

**Comment by cdh4u** [comment]
Implemented in PR:

https://github.com/cdh4u/draft-sdp-bundle/pull/33
